require("./TraitEvents.test");
require("./TraitService.test");
require("./TraitTask.test");
require("./TraitFetch.test");
require("./TraitDOM.test");
require("./TraitCSS.test");
require("./TraitTimeout.test");
require("./TraitInterval.test");
require("./TraitMutation.test");