name: Node CI

on:
  push:
    paths:
      - 'dist/**/*'
      - 'scripts/**/*'
      - 'src/**/*'
      - 'test/**/*'
      - 'package.json'
      - '*.js'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 19.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run test:bundle:prod
        npm run test:bundle:dev
        npm run build
        npm run test:bundle:prod
        npm run test:bundle:dev
      env:
        CI: true
